version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - openjdk-21-jdk
  tools:
    python: "3.14"
  jobs:
    pre_build:
      - ./gradlew javadoc

python:
  install:
    - method: pip
      path: ./docs/

sphinx:
  configuration: docs/docs/source/conf.py
